// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaiJeFvLD6LOcdvH07Z6-uYNZEMKtVAPs',
    appId: '1:23546495012:web:c7fd5c8329abed0aa3d8b1',
    messagingSenderId: '23546495012',
    projectId: 'primeshop-1eb1e',
    authDomain: 'primeshop-1eb1e.firebaseapp.com',
    storageBucket: 'primeshop-1eb1e.appspot.com',
    measurementId: 'G-EXHPCKZKEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6pwx3cGIztfNAMYvpbJqjPmB42b6B0ds',
    appId: '1:23546495012:android:5d657e3bc791892fa3d8b1',
    messagingSenderId: '23546495012',
    projectId: 'primeshop-1eb1e',
    storageBucket: 'primeshop-1eb1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXTFSGD6FfGkDpCTFV_dd6RIsXEL5QiMY',
    appId: '1:23546495012:ios:8d4717b07b87f582a3d8b1',
    messagingSenderId: '23546495012',
    projectId: 'primeshop-1eb1e',
    storageBucket: 'primeshop-1eb1e.appspot.com',
    iosBundleId: 'com.anas.primeshop',
  );
}
